### ISSUE TITLE
Error Lightstreamer::Errors::UnknownAdapterSetError

### ISSUE THREAD

**Issue by dmitryck** [richard-viney/lightstreamer#1]
Hello.
Thanx, very useful gem i see!

But some problem on start with example from your manual

```/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/lightstreamer-0.14/lib/lightstreamer/stream_connection.rb:48:in `connect': Lightstreamer::Errors::UnknownAdapterSetError```

**Comment by dmitryck** [comment]
I thought that this adapter_set and data_adapter using default existing classes in ligthstreamer
But there is no adapter config with DEMO and QUOTE_ADAPTER, there is only WELCOME and CHAT, ROOMBALL and etc from out of box

I've got it, issue can be closed..

**Comment by dmitryck** [comment]
Close #1

**Comment by lsg-richard** [comment]
Yes the adapter set and data adapter specified in the example code are setup for the Lightstreamer demo server. Other Lightstreamer servers will probably need different names there.

**Comment by richard-viney** [comment]
Yes the adapter set and data adapter specified in the example code are setup for the Lightstreamer demo server. Other Lightstreamer servers will probably need different names there.
